version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    assignees: ["jkueh"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule: { interval: "weekly" }
    assignees: ["jkueh"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly" }
    assignees: ["jkueh"]
