#!/usr/bin/env bash  
export HOSTED_ZONE_ID
export RECORD_SET
export RECORD_VALUE
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

CURL_INTERFACE="eth0"

HOSTED_ZONE_ID="HOSTED_ZONE_ID"
RECORD_SET="your.fancy.tld"
RECORD_VALUE="$(curl --interface ${CURL_INTERFACE} https://api.ipify.org)"
AWS_ACCESS_KEY_ID="AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY="AWS_SECRET_ACCESS_KEY"
AWS_SESSION_TOKEN="ThisIsOptional"

/usr/bin/env gorecord -